version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    resource_class: large
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install:
          node-version: "16"

      - restore_cache:
          key: playwright-browsers-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: playwright-browsers-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/ms-playwright

      - run: npx playwright install-deps

      - run: npm run build
      - run: npm test
      - run: npm run lint

workflows:
  test:
    jobs:
      - test
